.TH man 8 "16 Jan 2019" "0.1" "snetscan man page"
.SH NAME
snetscan \- Command line network scanner
.SH SYNOPSIS
snetscan --dev DEVICE [--help] [--version]
.SH DESCRIPTION
snetscan will print a list containing hosts connected to the network, displaying:
.IP \[bu] 2
IP Adress
.IP \[bu]
MAC Adress
.SH OPTIONS
.TP
\fB\-\-dev \fR
Set network interface
.TP
\fB\-\-help\fR
Prints help
.TP
\fB\-\-version\fR
Prints snetscan version
.SH BUGS
No known bugs. 
.SH AUTHOR
Dr-Noob (https://github.com/Dr-Noob)
